"""Add update_password_status column

Revision ID: 404a6e6c6b88
Revises: 237104ab5d52
Create Date: 2025-03-27 11:32:39.083346

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '404a6e6c6b88'
down_revision = '237104ab5d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('subhead', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('command_funds', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=16, scale=2),
               existing_nullable=True)
    op.drop_index('head_id', table_name='liabilities')
    op.drop_column('liabilities', 'subhead_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liabilities', sa.Column('subhead_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('head_id', 'liabilities', ['name'], unique=False)
    op.alter_column('command_funds', 'amount',
               existing_type=sa.DECIMAL(precision=16, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
    op.drop_column('assets', 'subhead')
    # ### end Alembic commands ###
