"""initial

Revision ID: 53a47db9f90b
Revises: 
Create Date: 2025-04-14 11:27:02.052444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '53a47db9f90b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corp_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corp_id', sa.Integer(), nullable=True),
    sa.Column('div_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corp_id'], ['corps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brigades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('div_id', sa.Integer(), nullable=True),
    sa.Column('brigade_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['div_id'], ['divs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brigade_id', sa.Integer(), nullable=True),
    sa.Column('unit_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remember_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('corp_id', sa.Integer(), nullable=True),
    sa.Column('div_id', sa.Integer(), nullable=True),
    sa.Column('brigade_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('appt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('update_password_status', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], ),
    sa.ForeignKeyConstraint(['corp_id'], ['corps.id'], ),
    sa.ForeignKeyConstraint(['div_id'], ['divs.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('causer_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('causer_id', sa.Integer(), nullable=True),
    sa.Column('properties', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch_uuid', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('my_custom_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['causer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_causer_type'), 'activity_log', ['causer_type'], unique=False)
    op.create_index(op.f('ix_activity_log_log_name'), 'activity_log', ['log_name'], unique=False)
    op.create_index(op.f('ix_activity_log_subject_type'), 'activity_log', ['subject_type'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subhead', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchased_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('depreciation_method_id', sa.Integer(), nullable=True),
    sa.Column('assign_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('salvage_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('useful_life', sa.Integer(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchased_by', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('place_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dispose_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sell_price', sa.Numeric(), nullable=True),
    sa.Column('sold_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gift_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disposed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disposed_date', sa.DateTime(), nullable=True),
    sa.Column('head_details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_in_hand', sa.Numeric(), nullable=True),
    sa.Column('cash_in_bank', sa.Numeric(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iban_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('heads', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subhead', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fund_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_new_entry_created', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('remaining_balance', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multi_ibn_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ibn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_balance_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('first_balance', sa.Numeric(), nullable=False),
    sa.Column('last_balance', sa.Numeric(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['fixed_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liability_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('liability_id', sa.Integer(), nullable=True),
    sa.Column('first_balance', sa.Numeric(), nullable=True),
    sa.Column('last_balance', sa.Numeric(), nullable=True),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['liability_id'], ['liabilities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('subheads', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['head_id'], ['heads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iban_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('received_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('old_amount', sa.Integer(), nullable=True),
    sa.Column('is_old_amount', sa.Boolean(), nullable=False),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('subhead_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['head_id'], ['heads.id'], ),
    sa.ForeignKeyConstraint(['iban_id'], ['multi_ibn_user.id'], ),
    sa.ForeignKeyConstraint(['subhead_id'], ['sub_heads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reciept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('corps_id', sa.Integer(), nullable=True),
    sa.Column('div_id', sa.Integer(), nullable=True),
    sa.Column('brigade_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('liability_id', sa.Integer(), nullable=True),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('subhead_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('head_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('place_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['heads.id'], ),
    sa.ForeignKeyConstraint(['subhead_id'], ['sub_heads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('command_funds')
    op.drop_table('sub_heads')
    op.drop_table('liability_balances')
    op.drop_table('investment_balance_histories')
    op.drop_table('multi_ibn_user')
    op.drop_table('liabilities')
    op.drop_table('heads')
    op.drop_table('fixed_assets')
    op.drop_table('balances')
    op.drop_table('assets')
    op.drop_index(op.f('ix_activity_log_subject_type'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_log_name'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_causer_type'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('brigades')
    op.drop_table('divs')
    op.drop_table('corps')
    op.drop_table('apartments')
    # ### end Alembic commands ###
