"""Add quantity field in assets 

Revision ID: cd7d7057f1d0
Revises: dbf02501dbd6
Create Date: 2025-05-02 11:15:37.231792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd7d7057f1d0'
down_revision = 'dbf02501dbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'quantity')
    # ### end Alembic commands ###
