"""Updated types and Fkey mapping in expencess

Revision ID: dbf02501dbd6
Revises: 53a47db9f90b
Create Date: 2025-04-30 13:32:35.812742

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbf02501dbd6'
down_revision = '53a47db9f90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'expenses', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'liabilities', ['liability_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'brigades', ['brigade_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'corps', ['corps_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'fixed_assets', ['fixed_asset_id'], ['id'])
    op.alter_column('fixed_assets', 'asset_details',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('fixed_assets', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=16, scale=2),
               existing_nullable=True)
    op.create_foreign_key(None, 'fixed_assets', 'multi_ibn_user', ['iban_id'], ['id'])
    op.alter_column('investment_balance_histories', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('liabilities', 'fund_details',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('liabilities', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=16, scale=2),
               existing_nullable=True)
    op.alter_column('liability_balances', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('liability_balances', 'current_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=16, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('liability_balances', 'current_amount',
               existing_type=sa.DECIMAL(precision=16, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
    op.alter_column('liability_balances', 'description',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('liabilities', 'amount',
               existing_type=sa.DECIMAL(precision=16, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
    op.alter_column('liabilities', 'fund_details',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('investment_balance_histories', 'description',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'fixed_assets', type_='foreignkey')
    op.alter_column('fixed_assets', 'amount',
               existing_type=sa.DECIMAL(precision=16, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
    op.alter_column('fixed_assets', 'asset_details',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    # ### end Alembic commands ###
